import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Providers } from "./providers";

const monster = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "w-screen max-w-screen-2xl h-screen overflow-hidden bg-background font-sans antialiased", monster.className
        )}
      >
        <main className="overflow-y-scroll w-full">
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
